language: python
python:
  - "2.7"
#  - "pypy"
#  - "3.3"
#  - "3.4"

os:
  - linux
#  - osx

env:                                                                           
  - PYCOIN_NATIVE=openssl

install:
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt
  - pip install meliae
  - python setup.py install

script:
  - pep8 storjterms
  - pep8 examples
  - pep8 tests
  - travis_wait coverage run --source="storjterms" setup.py test
  - coverage report --fail-under=90

after_success:
  - coveralls

notifications:
  slack: storjcommunity:TZfUO9ycY8R9UYwztWZTo0jk
  email: false
