language: python
python:
  - "2.7"
#  - "pypy"
#  - "3.3"
#  - "3.4"

os:
  - linux
#  - osx

env:                                                                           
  - PYCOIN_NATIVE=openssl



install:
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt
  - python setup.py install
  - coverage run --source="storjterms" -m storjterms.api startserver --hostname="127.0.0.1" --port=7000 < /dev/null &>/dev/null &


script:
  - pep8 storjterms
  - pep8 tests
  - bash -c "source <(curl -s https://raw.githubusercontent.com/Storj/storjspec/master/test_storjterms_compatibility.sh)"
  - travis_wait coverage run --source="storjterms" setup.py test
  #- coverage report --fail-under=80

after_success:
  - coveralls

notifications:
  slack: storjcommunity:TZfUO9ycY8R9UYwztWZTo0jk
  email: false
