language: python
python:
  - "2.7"


os:
  - linux


env:                                                                           
  - PYCOIN_NATIVE=openssl


before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq screen


install:
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt
  - python setup.py install


script:
  - bash test.sh


after_success:
  - coveralls


notifications:
  slack: storjcommunity:TZfUO9ycY8R9UYwztWZTo0jk
  email: false
